src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Users implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_siret;

    /**
     * @ORM\OneToMany(targetEntity=Planning::class, mappedBy="Users", orphanRemoval=true)
     */
    private $plannings;

    /**
     * @ORM\OneToMany(targetEntity=Vehicule::class, mappedBy="users")
     */
    private $vehicules;

    /**
     * @ORM\OneToMany(targetEntity=Service::class, mappedBy="users", orphanRemoval=true)
     */
    private $services;

    /**
     * @ORM\OneToMany(targetEntity=Entreprise::class, mappedBy="users")
     */
    private $entreprises;

    /**
     * @ORM\OneToMany(targetEntity=Galerie::class, mappedBy="users")
     */
    private $galeries;

    public function __construct()
    {
        $this->plannings = new ArrayCollection();
        $this->vehicules = new ArrayCollection();
        $this->services = new ArrayCollection();
        $this->entreprises = new ArrayCollection();
        $this->galeries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getNumeroSiret(): ?string
    {
        return $this->numero_siret;
    }

    public function setNumeroSiret(string $numero_siret): self
    {
        $this->numero_siret = $numero_siret;

        return $this;
    }

    /**
     * @return Collection|Planning[]
     */
    public function getPlannings(): Collection
    {
        return $this->plannings;
    }

    public function addPlanning(Planning $planning): self
    {
        if (!$this->plannings->contains($planning)) {
            $this->plannings[] = $planning;
            $planning->setUsers($this);
        }

        return $this;
    }

    public function removePlanning(Planning $planning): self
    {
        if ($this->plannings->removeElement($planning)) {
            // set the owning side to null (unless already changed)
            if ($planning->getUsers() === $this) {
                $planning->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Vehicule[]
     */
    public function getVehicules(): Collection
    {
        return $this->vehicules;
    }

    public function addVehicule(Vehicule $vehicule): self
    {
        if (!$this->vehicules->contains($vehicule)) {
            $this->vehicules[] = $vehicule;
            $vehicule->setUsers($this);
        }

        return $this;
    }

    public function removeVehicule(Vehicule $vehicule): self
    {
        if ($this->vehicules->removeElement($vehicule)) {
            // set the owning side to null (unless already changed)
            if ($vehicule->getUsers() === $this) {
                $vehicule->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Service[]
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Service $service): self
    {
        if (!$this->services->contains($service)) {
            $this->services[] = $service;
            $service->setUsers($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->services->removeElement($service)) {
            // set the owning side to null (unless already changed)
            if ($service->getUsers() === $this) {
                $service->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Entreprise[]
     */
    public function getEntreprises(): Collection
    {
        return $this->entreprises;
    }

    public function addEntreprise(Entreprise $entreprise): self
    {
        if (!$this->entreprises->contains($entreprise)) {
            $this->entreprises[] = $entreprise;
            $entreprise->setUsers($this);
        }

        return $this;
    }

    public function removeEntreprise(Entreprise $entreprise): self
    {
        if ($this->entreprises->removeElement($entreprise)) {
            // set the owning side to null (unless already changed)
            if ($entreprise->getUsers() === $this) {
                $entreprise->setUsers(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Galerie[]
     */
    public function getGaleries(): Collection
    {
        return $this->galeries;
    }

    public function addGalery(Galerie $galery): self
    {
        if (!$this->galeries->contains($galery)) {
            $this->galeries[] = $galery;
            $galery->setUsers($this);
        }

        return $this;
    }

    public function removeGalery(Galerie $galery): self
    {
        if ($this->galeries->removeElement($galery)) {
            // set the owning side to null (unless already changed)
            if ($galery->getUsers() === $this) {
                $galery->setUsers(null);
            }
        }

        return $this;
    }
}

src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email' , EmailType::class)
            ->add('roles')
            ->add('password' , PasswordType::class)
            ->add('isVerified')
            ->add('telephone' , TelType::class)
            ->add('status' , TextType::class)
            ->add('numero_siret' , NumberType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
        ]);
    }
}

src/Controller/UsersController.php
<?php

namespace App\Controller;

use App\Entity\Users;
use App\Form\UsersType;
use App\Repository\UsersRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/users")
 */
class UsersController extends AbstractController
{
    /**
     * @Route("/", name="users_index", methods={"GET"})
     */
    public function index(UsersRepository $usersRepository): Response
    {
        return $this->render('users/index.html.twig', [
            'users' => $usersRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="users_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = new Users();
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('users_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('users/new.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="users_show", methods={"GET"})
     */
    public function show(Users $user): Response
    {
        return $this->render('users/show.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="users_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Users $user): Response
    {
        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('users_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('users/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="users_delete", methods={"POST"})
     */
    public function delete(Request $request, Users $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('users_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/users/_delete_form.html.twig
<form method="post" action="{{ path('users_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn"><i class="fa fa-trash-o" style="color: red"></i></button>
</form>

templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Users{% endblock %}

{% block body %}
 <div id="right-panel" class="right-panel">
    <div class="content">
        <div class="animated fadeIn">
            <!-- Widgets  -->
            <div class="row">
                <div class="col-md-7">
                    <div class="card">
                        <div class="card-header card-pr">
                            <strong class="card-title">EDITER LES INFORMATIONS DE L'UTILISATEUR  </strong>
                        </div>
                        <div class="card-body">
                               {{ include('users/_form.html.twig', {'button_label': 'Update'}) }}

                           <a href="{{ path('users_index') }}">Consulter les utilisateurs </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 </div>
</div> 

 
    
{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div id="right-panel" class="right-panel">
    <div class="content">
        <div class="animated fadeIn">
            <!-- Widgets  -->
            <div class="row">
                <div class="col-md-10">
                    <div class="card">
                        <div class="card-header bg-danger mb-3 text-white">
                            <strong class="card-title">GESTION UTILISATEURS </strong>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered " id="bootstrap-data-table">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Email</th>
                                        <th>Telephone</th>
                                        <th>Status</th>
                                        <th>Numero_siret</th>
                                        <th>actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for user in users %}
                                    <tr>
                                        <td>{{ user.id }}</td>
                                        <td>{{ user.email }}</td>
                                        
                                      
                                        <td>{{ user.telephone }}</td>
                                        <td>{{ user.status }}</td>
                                        <td>{{ user.numeroSiret }}</td>
                                        <td>
                                         <div style="display: inline-block;padding-left:2%"> {{ include('users/_delete_form.html.twig') }} </div> 
                                          
                                            <a href="{{ path('users_show', {'id': user.id}) }}"><i style="font-size:22px ; color:green" class="fa fa-info-circle"> </i></a>
                                        </td>
                                       
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="9">no records found</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 </div>
</div>
{% endblock %}

templates/users/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Users{% endblock %}

{% block body %}
    <h1>Create new Users</h1>

    {{ include('users/_form.html.twig') }}

    <a href="{{ path('users_index') }}">back to list</a>
{% endblock %}

templates/users/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
   <div id="right-panel" class="right-panel">
    <div class="content">
        <div class="animated fadeIn">
            <!-- Widgets  -->
            <div class="row">
                <div class="col-md-10">
                    <div class="card">
                        <div class="card-header card-pr">
                            <strong class="card-title">DESCRIPTION DE L'UTILISATEUR  </strong>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered ">
                                <tbody>
                                    <tr>
                                        <th>Id</th>
                                        <td>{{ user.id }}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td>{{ user.email }}</td>
                                    </tr>
                                    <tr>
                                        <th>validation de compte </th>
                                        <td>{{ user.isVerified ? 'Yes' : 'No' }}</td>
                                    </tr>
                                    <tr>
                                        <th>Telephone</th>
                                        <td>{{ user.telephone }}</td>
                                    </tr>
                                    <tr>
                                        <th>Status</th>
                                        <td>{{ user.status }}</td>
                                    </tr>
                                    <tr>
                                        <th>Numero de siret</th>
                                        <td>{{ user.numeroSiret }}</td>
                                    </tr>
                                </tbody>
                            </table>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
 </div>
</div>   

   

    <a href="{{ path('users_index') }}">back to list</a>

    <a href="{{ path('users_edit', {'id': user.id}) }}">edit</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}